spring.application.name=duralap

# MongoDB connection
spring.data.mongodb.uri=mongodb+srv://sazib1008:qHJ9ecgQPqNsS3NY@cluster0.fjyvxzs.mongodb.net/duralap?appName=Cluster0

# Redis connection
spring.data.redis.host=redis-16687.c85.us-east-1-2.ec2.cloud.redislabs.com
spring.data.redis.port=16687
spring.data.redis.username=default
spring.data.redis.password=IQ7zsPZlUblNxXoKPtzeR6H541EEjyXU
spring.data.redis.ssl.enabled=true

# JWT Configuration
app.jwt.secret=${JWT_SECRET:mySecretKeyForDuralapAppThatShouldBeLongerThan256Bits}
app.jwt.expiration-in-ms=${JWT_EXPIRATION:86400000}
app.jwt.refresh-expiration-in-ms=${JWT_REFRESH_EXPIRATION:604800000}

# Server configuration
server.port=8080

# Logging
logging.level.org.springframework.security=DEBUG
logging.level.com.example.duralap.security=DEBUG

