package com.example.duralap.config

import com.example.duralap.consumers.WebRtcSignalingSubscriber
import org.springframework.context.annotation.Bean
import org.springframework.context.annotation.Configuration
import org.springframework.data.redis.connection.RedisConnectionFactory
import org.springframework.data.redis.listener.PatternTopic
import org.springframework.data.redis.listener.RedisMessageListenerContainer

@Configuration
class RedisPubSubConfig {

    @Bean
    fun redisMessageListenerContainer(
        connectionFactory: RedisConnectionFactory,
        webRtcSignalingSubscriber: WebRtcSignalingSubscriber
    ): RedisMessageListenerContainer {
        val container = RedisMessageListenerContainer()
        container.setConnectionFactory(connectionFactory)
        
        // Listen to all signals dynamically generated by the CallSignalingService
        // routingKeys match the format: "rtc:signal:user:{userId}"
        container.addMessageListener(webRtcSignalingSubscriber, PatternTopic("rtc:signal:user:*"))
        
        return container
    }
}
